backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "casos"
    label: "Casos"
    folder: "cases"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Estado", name: "estado", widget: "select", options: ["Activo", "Archivado"] }
